name: Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Checkout submodules # checkout rest
      shell: bash
      run: |
        git submodule sync --recursive
        git submodule update --init --force --recursive --depth=1
    - uses: actions/setup-node@v2
      with:
        node-version: '14'
    - run: git submodule sync --recursive
    - run: npm ci
    - run: npm run jest
    - run: npm run e2e
