name: Tests

on:
  push:
    branches: [ master ]

jobs:
  test:
    runs-on: ${{ matrix.os }}
  
    strategy:                                              
      fail-fast: false
      matrix:                                              
        node-version: [16.x]
        os: [ubuntu-latest, macOS-latest, windows-latest]

    steps:
    - uses: actions/checkout@v2
    - name: Checkout submodules # checkout rest
      shell: bash
      run: |
        git submodule sync --recursive
        git submodule update --init --force --recursive --depth=1
    - uses: actions/setup-node@v2
      with:
        node-version: '16'
        cache: 'npm'
    
    - name: clone jpegjs
      run: git submodule sync --recursive

    - name: install dependencies
      run: npm ci

    - name: build
      run: npm run build

    - name: run jest tests
      run: npm run test:jest

    - name: run karma tests
      run: npm run test:karma:headless